In [3]:
#creating 1D array
list1=[0,1,2,3,4]
list1

[0, 1, 2, 3, 4]

In [4]:
#this is simple list but not numpy array
arr1= np.array(list1)
arr1

array([0, 1, 2, 3, 4])

In [ ]:
#difference between array and list: arrays are designed for vectorised functions.Once an array is defined with a particular size, its size cannot be increased although the list size can be increased.

In [6]:
list1.append(5)
list1

[0, 1, 2, 3, 4, 5]

In [7]:
#Here the size of the list of increased.Another difference between list and array is the set of operations. For example, it is easier to add/subtract a particular number from all elements of an array than in list

In [8]:
arr1= arr1+2

In [9]:
arr1

array([2, 3, 4, 5, 6])

In [10]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]
arr2d= np.array(list2)

In [11]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [12]:
#type of the array
type(arr2d)

numpy.ndarray

In [13]:
arr2d.dtype

dtype('int32')

In [15]:
#create an array with custom datatype
arr2d= np.array(list2,dtype='float')

In [16]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [17]:
arr2d.dtype

dtype('float64')

In [19]:
arr2d.astype('int') #changing to int datatype

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [20]:
arr2d.astype('str') #.appears as arr2d is still float type

array([['1.0', '1.0', '1.0'],
       ['2.0', '2.0', '2.0'],
       ['3.0', '3.0', '3.0']], dtype='<U32')

In [21]:
#Another difference
list1.append('6')

In [22]:
list1

[0, 1, 2, 3, 4, 5, '6']

In [23]:
#'6' is string here. so list is colllection of multiple datatype unlike array.
#convert numpy array to list
np2list= arr2d.tolist()

In [24]:
np2list

[[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]]

In [25]:
arr2d.tostring() #converted to byte string

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

In [26]:
arr2d.tobytes()

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

In [27]:
#dtype and shape

In [29]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [30]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [31]:
arr2d.astype('float')

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [33]:
print("shape: ",arr2d.shape)

shape:  (3, 3)


In [35]:
print("Data-Type: ",arr2d.dtype)

Data-Type:  float64


In [36]:
print("size: ",arr2d.size)

size:  9


In [37]:
print("Dimension: ",arr2d.ndim)

Dimension:  2


In [40]:
#extract specific element
arr2d[1][1] #[R][C]

2.0

In [41]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [42]:
boolarr = arr2d<3

In [43]:
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [44]:
#to change the rows
arr2d[::-1,]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [45]:
#transpose
arr2d[::-1,::-1]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [46]:
#represnt np.nan ,np.inf
np.nan #not a number

nan

In [48]:
np.inf #infinity, data computation cannot be performed

inf

In [49]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [50]:
#insert a number
arr2d[0][0] = np.nan
arr2d[1][1] =np.inf

In [51]:
arr2d

array([[nan,  1.,  1.],
       [ 2., inf,  2.],
       [ 3.,  3.,  3.]])

In [53]:
#check for null values, infinite number or nan?
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [54]:
np.isinf(arr2d)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [55]:
#replace any number
missing_flag = np.isnan(arr2d) | np.isinf(arr2d)

In [56]:
missing_flag

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [57]:
#replace inf & nan with zero
arr2d[missing_flag]=0
arr2d

array([[0., 1., 1.],
       [2., 0., 2.],
       [3., 3., 3.]])

In [58]:
#statistical operations on numpy array
arr2d.mean()

1.6666666666666667

In [59]:
arr2d.max()

3.0

In [60]:
arr2d.min()

0.0

In [61]:
arr2d.std()

1.1547005383792515

In [62]:
arr2d.var()

1.3333333333333333

In [63]:
arr2d.squeeze()

array([[0., 1., 1.],
       [2., 0., 2.],
       [3., 3., 3.]])

In [65]:
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])  
print ("Input array : ", in_arr)  
print("Shape of input array : ", in_arr.shape)   

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)


In [66]:
out_arr = np.squeeze(in_arr)  
print ("output squeezed array : ", out_arr) 
print("Shape of output array : ", out_arr.shape)  

output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


In [67]:
arr2d.cumsum()

array([ 0.,  1.,  2.,  4.,  4.,  6.,  9., 12., 15.])

In [68]:
#creating array from existing array
arr= arr2d[:2,:2]
arr

array([[0., 1.],
       [2., 0.]])

In [71]:
arr2d[1:3,1:3]

array([[0., 2.],
       [3., 3.]])

In [72]:
arr2d[1:3,1:2]

array([[0.],
       [3.]])

In [73]:
#reshape the array
arr2d

array([[0., 1., 1.],
       [2., 0., 2.],
       [3., 3., 3.]])

In [74]:
arr2d.reshape(1,9)

array([[0., 1., 1., 2., 0., 2., 3., 3., 3.]])

In [75]:
arr2d.reshape(9,1)

array([[0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [76]:
arr2d.flatten() #2d is converted into 1d
# a copy is created

array([0., 1., 1., 2., 0., 2., 3., 3., 3.])

In [79]:
b=arr2d.ravel()
# a reference is created

In [80]:
#diff between flatten and ravel is
#ravel uses the reference to the original array.Any changes willaffect the parent as well.
b[0]=-1
arr2d

array([[-1.,  1.,  1.],
       [ 2.,  0.,  2.],
       [ 3.,  3.,  3.]])

In [81]:
#sequence , repition of random numbers
np.arange(1,5)

array([1, 2, 3, 4])

In [84]:
np.arange(1,5,dtype='float')

array([1., 2., 3., 4.])

In [85]:
np.arange(1,5,dtype='int')

array([1, 2, 3, 4])

In [86]:
np.arange(1,5,dtype='object')

array([1, 2, 3, 4], dtype=object)

In [87]:
np.arange(2,50,2) #even no between 2 and 50

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [89]:
np.linspace(1,50,100) #100 nos are generated between 1 and 50 (here exact count can be specified)no are generated in linear space

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [90]:
np.logspace(1,50,10) #10 numbers on log space

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [92]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [93]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
a=[1,2,3]

In [95]:
np.tile(a,3) #repaet array 3 times

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [97]:
np.repeat(a,3) #repeat each element 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [98]:
np.repeat(arr2d,3)

array([-1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  0.,
        0.,  0.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.])

In [99]:
#generate random numbers
np.random.rand(1,3) #1*3 matrix,these generated numbers are uniformly distributed

array([[0.48817046, 0.69810212, 0.95659324]])

In [100]:
np.random.rand(3,3) 

array([[0.15503162, 0.56398301, 0.73030306],
       [0.26992077, 0.39016438, 0.26067684],
       [0.08762378, 0.1700684 , 0.64251456]])

In [101]:
#for normal distributed random numbers, use
np.random.randn(3,3)

array([[ 0.31699297, -0.83881301, -1.22025835],
       [-0.08881897,  0.66504757, -0.91232819],
       [-0.2976559 ,  0.1695125 ,  0.04933316]])

In [102]:
#generate random no with integer
np.random.randint(0,10)

5

In [103]:
np.random.randint(0,10,[3,3]) #[3,3] is the size

array([[3, 4, 3],
       [3, 2, 6],
       [3, 6, 6]])

In [104]:
#reproduce same random number
np.random.seed(0)
np.random.randint(0,10,[3,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [105]:
np.random.seed(1)
np.random.randint(0,10,[3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [106]:
#unique items and counts
np.unique(arr2d)

array([-1.,  0.,  1.,  2.,  3.])

In [107]:
uni,cou = np.unique(arr2d,return_counts=True)
uni

array([-1.,  0.,  1.,  2.,  3.])

In [108]:
cou

array([1, 1, 2, 2, 3])

In [1]:
#part 2 https://www.youtube.com/watch?v=04I9eoEn8Rs

In [3]:
#get index location based on given 
arr= np.array([10,23,45,6,8,90,12,34,67])
arr

array([10, 23, 45,  6,  8, 90, 12, 34, 67])

In [6]:
#print array index where element is greater than 10
index_gt10= np.where(arr>10)

In [9]:
index_gt10

(array([1, 2, 5, 6, 7, 8], dtype=int32),)

In [10]:
arr[index_gt10]  #print values with index

array([23, 45, 90, 12, 34, 67])

In [14]:
#above 3 steps can be combined as
arr[arr>10]

array([23, 45, 90, 12, 34, 67])

In [17]:
arr> 10 #boolean true based on condition/logical condition

array([False,  True,  True, False, False,  True,  True,  True,  True])

In [19]:
np.where(arr>10,'gt10','lt10') #print based on condition

array(['lt10', 'gt10', 'gt10', 'lt10', 'lt10', 'gt10', 'gt10', 'gt10',
       'gt10'], dtype='<U4')

In [20]:
arr

array([10, 23, 45,  6,  8, 90, 12, 34, 67])

In [21]:
arr.max()

90

In [22]:
#index of max value
arr.argmax()

5

In [23]:
# value of min
arr[arr.argmin()]

6

In [24]:
#index of min
arr.argmin()

3

In [25]:
#read and write txt file

In [26]:
#2 methods
#np.genfromtxt  where multiple data type dataset
#np.loadtxt()  where same dtatype datatset

In [55]:
data=np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=1,filling_values=-1000,dtype='float') #all string are converted into -1000

In [56]:
data.shape

(392, 9)

In [57]:
data[:3] # 1st 3 rows

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [58]:
np.set_printoptions(suppress=True) #hide scientif notation format
data[:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [59]:
data2= np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=1,dtype=object)
data2[:3]

array([[b'18', b'8', b'307', b'130', b'3504', b'12', b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', b'165', b'3693', b'11.5', b'70', b'1',
        b'"buick skylark 320"'],
       [b'18', b'8', b'318', b'150', b'3436', b'11', b'70', b'1',
        b'"plymouth satellite"']], dtype=object)

In [60]:
#save this to csv format
np.savetxt('data.csv',data,delimiter=',')

In [63]:
data2

array([[b'18', b'8', b'307', ..., b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', ..., b'70', b'1', b'"buick skylark 320"'],
       [b'18', b'8', b'318', ..., b'70', b'1', b'"plymouth satellite"'],
       ...,
       [b'32', b'4', b'135', ..., b'82', b'1', b'"dodge rampage"'],
       [b'28', b'4', b'120', ..., b'82', b'1', b'"ford ranger"'],
       [b'31', b'4', b'119', ..., b'82', b'1', b'"chevy s-10"']],
      dtype=object)

In [64]:
#save numpy array
np.save('data.npy',data2)

In [65]:
np.savez('data2.npz',data,data2) #save mu;tiple numpy array

In [67]:
#loading saved file
d= np.load('data.npy',allow_pickle = True)

In [68]:
d

array([[b'18', b'8', b'307', ..., b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', ..., b'70', b'1', b'"buick skylark 320"'],
       [b'18', b'8', b'318', ..., b'70', b'1', b'"plymouth satellite"'],
       ...,
       [b'32', b'4', b'135', ..., b'82', b'1', b'"dodge rampage"'],
       [b'28', b'4', b'120', ..., b'82', b'1', b'"ford ranger"'],
       [b'31', b'4', b'119', ..., b'82', b'1', b'"chevy s-10"']],
      dtype=object)

In [69]:
d2= np.load('data2.npz',allow_pickle = True)

In [70]:
d2 #zip file

In [71]:
#to get the files
d2.files

['arr_0', 'arr_1']

In [72]:
d2['arr_0'] #1st element

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [73]:
d2['arr_1']

array([[b'18', b'8', b'307', ..., b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', ..., b'70', b'1', b'"buick skylark 320"'],
       [b'18', b'8', b'318', ..., b'70', b'1', b'"plymouth satellite"'],
       ...,
       [b'32', b'4', b'135', ..., b'82', b'1', b'"dodge rampage"'],
       [b'28', b'4', b'120', ..., b'82', b'1', b'"ford ranger"'],
       [b'31', b'4', b'119', ..., b'82', b'1', b'"chevy s-10"']],
      dtype=object)

In [74]:
#concatenate 2 numpy array-row wise and col wise

In [75]:
arr1= np.zeros([4,4])
arr2= np.ones([4,4])

In [76]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
#np.concatenate , np.vstack, np.r

In [79]:
np.concatenate([arr1,arr2],axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
np.vstack([arr1,arr2])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.r_[arr1,arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
np.concatenate([arr1,arr2],axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [83]:
np.hstack([arr1,arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [84]:
np.c_[arr1,arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [85]:
#sorting an array

In [86]:
arr = np.random.randint(1,10,size=[10,5])
arr

array([[1, 7, 2, 7, 6],
       [4, 5, 2, 8, 3],
       [1, 7, 2, 4, 2],
       [7, 8, 8, 4, 5],
       [4, 2, 1, 3, 4],
       [4, 6, 8, 2, 5],
       [1, 5, 9, 1, 2],
       [3, 3, 6, 1, 1],
       [9, 5, 1, 7, 8],
       [6, 1, 4, 3, 5]])

In [88]:
np.sort(arr) #sorting along the axis

array([[1, 2, 6, 7, 7],
       [2, 3, 4, 5, 8],
       [1, 2, 2, 4, 7],
       [4, 5, 7, 8, 8],
       [1, 2, 3, 4, 4],
       [2, 4, 5, 6, 8],
       [1, 1, 2, 5, 9],
       [1, 1, 3, 3, 6],
       [1, 5, 7, 8, 9],
       [1, 3, 4, 5, 6]])

In [90]:
#sort along column
np.sort(arr,axis=0)

array([[1, 1, 1, 1, 1],
       [1, 2, 1, 1, 2],
       [1, 3, 2, 2, 2],
       [3, 5, 2, 3, 3],
       [4, 5, 2, 3, 4],
       [4, 5, 4, 4, 5],
       [4, 6, 6, 4, 5],
       [6, 7, 8, 7, 5],
       [7, 7, 8, 7, 6],
       [9, 8, 9, 8, 8]])

In [91]:
#in the above, row order is not maintained
arr[:,0]

array([1, 4, 1, 7, 4, 4, 1, 3, 9, 6])

In [94]:
sorted_index= arr[:,0].argsort() #it gives the index

In [96]:
arr[sorted_index] #sort along a simple column

array([[1, 7, 2, 7, 6],
       [1, 7, 2, 4, 2],
       [1, 5, 9, 1, 2],
       [3, 3, 6, 1, 1],
       [4, 5, 2, 8, 3],
       [4, 2, 1, 3, 4],
       [4, 6, 8, 2, 5],
       [6, 1, 4, 3, 5],
       [7, 8, 8, 4, 5],
       [9, 5, 1, 7, 8]])

In [98]:
#working with dates
dat= np.datetime64('2020-06-23 23:10:06 ')
dat

numpy.datetime64('2020-06-23T23:10:06')

In [99]:
dat+1 #add 1 sec

numpy.datetime64('2020-06-23T23:10:07')

In [100]:
dat+1000 #16*60+40

numpy.datetime64('2020-06-23T23:26:46')

In [101]:
#add days
oneday= np.timedelta64(1,'D')
oneday

numpy.timedelta64(1,'D')

In [102]:
dat+ oneday

numpy.datetime64('2020-06-24T23:10:06')

In [103]:
oneminute= np.timedelta64(1,"m")

In [104]:
dat+oneminute

numpy.datetime64('2020-06-23T23:11:06')

In [106]:
#sequence of dates
dates= np.arange(np.datetime64('2020-06-24'),np.datetime64('2021-06-24'))
dates

array(['2020-06-24', '2020-06-25', '2020-06-26', '2020-06-27',
       '2020-06-28', '2020-06-29', '2020-06-30', '2020-07-01',
       '2020-07-02', '2020-07-03', '2020-07-04', '2020-07-05',
       '2020-07-06', '2020-07-07', '2020-07-08', '2020-07-09',
       '2020-07-10', '2020-07-11', '2020-07-12', '2020-07-13',
       '2020-07-14', '2020-07-15', '2020-07-16', '2020-07-17',
       '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21',
       '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25',
       '2020-07-26', '2020-07-27', '2020-07-28', '2020-07-29',
       '2020-07-30', '2020-07-31', '2020-08-01', '2020-08-02',
       '2020-08-03', '2020-08-04', '2020-08-05', '2020-08-06',
       '2020-08-07', '2020-08-08', '2020-08-09', '2020-08-10',
       '2020-08-11', '2020-08-12', '2020-08-13', '2020-08-14',
       '2020-08-15', '2020-08-16', '2020-08-17', '2020-08-18',
       '2020-08-19', '2020-08-20', '2020-08-21', '2020-08-22',
       '2020-08-23', '2020-08-24', '2020-08-25', '2020-

In [108]:
dates= np.arange(np.datetime64('2020-06-24'),np.datetime64('2021-06-24'),2) #2 day gap
dates

array(['2020-06-24', '2020-06-26', '2020-06-28', '2020-06-30',
       '2020-07-02', '2020-07-04', '2020-07-06', '2020-07-08',
       '2020-07-10', '2020-07-12', '2020-07-14', '2020-07-16',
       '2020-07-18', '2020-07-20', '2020-07-22', '2020-07-24',
       '2020-07-26', '2020-07-28', '2020-07-30', '2020-08-01',
       '2020-08-03', '2020-08-05', '2020-08-07', '2020-08-09',
       '2020-08-11', '2020-08-13', '2020-08-15', '2020-08-17',
       '2020-08-19', '2020-08-21', '2020-08-23', '2020-08-25',
       '2020-08-27', '2020-08-29', '2020-08-31', '2020-09-02',
       '2020-09-04', '2020-09-06', '2020-09-08', '2020-09-10',
       '2020-09-12', '2020-09-14', '2020-09-16', '2020-09-18',
       '2020-09-20', '2020-09-22', '2020-09-24', '2020-09-26',
       '2020-09-28', '2020-09-30', '2020-10-02', '2020-10-04',
       '2020-10-06', '2020-10-08', '2020-10-10', '2020-10-12',
       '2020-10-14', '2020-10-16', '2020-10-18', '2020-10-20',
       '2020-10-22', '2020-10-24', '2020-10-26', '2020-

In [110]:
#vectorize()- a function that can work on each element of an array

In [115]:
def foo(x): # if remainder then square it otherwise divide by 2
    if x%2==1: 
        return x**2
    else:
        return x/2
foo(11)

121

In [112]:
foo_v= np.vectorize(foo,otypes=[float])

In [113]:
arr

array([[1, 7, 2, 7, 6],
       [4, 5, 2, 8, 3],
       [1, 7, 2, 4, 2],
       [7, 8, 8, 4, 5],
       [4, 2, 1, 3, 4],
       [4, 6, 8, 2, 5],
       [1, 5, 9, 1, 2],
       [3, 3, 6, 1, 1],
       [9, 5, 1, 7, 8],
       [6, 1, 4, 3, 5]])

In [114]:
foo_v(arr)

array([[ 1., 49.,  1., 49.,  3.],
       [ 2., 25.,  1.,  4.,  9.],
       [ 1., 49.,  1.,  2.,  1.],
       [49.,  4.,  4.,  2., 25.],
       [ 2.,  1.,  1.,  9.,  2.],
       [ 2.,  3.,  4.,  1., 25.],
       [ 1., 25., 81.,  1.,  1.],
       [ 9.,  9.,  3.,  1.,  1.],
       [81., 25.,  1., 49.,  4.],
       [ 3.,  1.,  2.,  9., 25.]])